security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path:  /login
                check_path:  /check
            logout:
                path:   /logoff
                target: /
    access_denied_url: /denegado
    access_control:
        - { path: ^/perfil        , roles: ROLE_USER }
        - { path: ^/me-apunto-a-* , roles: ROLE_USER }
        - { path: ^/admin         , roles: ROLE_ADMIN }
        - { path: ^/registro      , roles: IS_AUTHENTICATED_ANONYMOUSLY }

    providers:
        main:
            providers: [in_memory, user_db]
        in_memory:
            users:
                desymfony: { password: desymfony, roles: 'ROLE_ADMIN' }
                admin:     { password: admin, roles: 'ROLE_ADMIN' }
        user_db:
            entity: { class: Desymfony\DesymfonyBundle\Entity\Usuario, property: email }
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Desymfony\DesymfonyBundle\Entity\Usuario: sha512
